### ISSUE TITLE
Executive memberships

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popolo-viewer-sinatra#24]
Display Executive-level memberships per Person, and per-Government, including pivoting to a view of who else has held that same position over time.

**Comment by tmtmtmtm** [comment]
Depends on https://github.com/everypolitician/everypolitician/issues/178

**Comment by chrismytton** [comment]
Related to https://github.com/everypolitician/everypolitician/issues/178

**Comment by chrismytton** [comment]
Have done a prototype of this in https://github.com/everypolitician/viewer-sinatra/pull/13600.

Things that came out of the prototype:

- [ ] Need to make accessing the `unstable/positions/csv` file a little less involve. For now this complexity can probably just be hidden in a class, then it can be moved to ep-ruby at a later point.
- [ ] Make sure we filter the list of positions to only those that have `type = cabinet`  in the CSV
- [ ] Need to filter positions to show only those for the current term
- [ ] Probably best to add position data to the person class, rather than passing another constructor argument to `PersonCard`

The prototype was useful as a guiding light, but I think for the next stage we probably want to throw that away and do a fresh version using TDD.

**Comment by chrismytton** [comment]
# TODO

- [ ] Add classes to the `lib/everypolitician_extensions.rb` file for interacting with position data. Prototype of this in https://github.com/everypolitician/viewer-sinatra/pull/15608.
  - [ ] `Everypolitician::Position` which represents an individual position held
  - [ ] `Everypolitician::Positions` for filtering and interacting with positions data
    - [ ] Should be able to filter by `type` (we just want to show the `cabinet` positions initially)
    - [ ] Should be able to filter by term, i.e. "give me all the positions between these two dates"
- [ ] Add `Everypolitician::UnstablePositionCSV` class for getting the position data out of the `unstable/positions.csv` file. https://github.com/everypolitician/viewer-sinatra/issues/15606
  - This can then be replaced with another class when we decide where the position data will live.
- [ ] Allow `Everypolitician::Popolo::Person` instances to access the position data for the person
