### ISSUE TITLE
Term Table design

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popolo-viewer-sinatra#96]
We currently have a simple table of members during a term, e.g. `/finland/term_table`

![term table 2015-04-27 at 14 54 51](https://cloud.githubusercontent.com/assets/57483/7348924/679993dc-eced-11e4-83ac-3fe63a38c6a2.png)

Party changes, etc, are simply shown as grouped rows:
![change party 2015-04-27 at 14 55 19](https://cloud.githubusercontent.com/assets/57483/7348938/79db2fc4-eced-11e4-8712-0c8c3bea8ea8.png)

Things we'll want to add to this include:
- [x] Handling bicameral legislatures, perhaps with a 'tabbed' interface to switch between the houses. #97 
- [x] A display for the current breakdown of Parties  — Conservative 302, Labour 256, Liberal Democrats 56, etc (where possible, Government Parties will be split out/highlighted separately) #98 
- [x] Filtering/Sorting the list of People
- [x] Where we have data for other terms, simple navigation to those, either just in forward/back buttons, or perhaps a little table like at the bottom of similar Wikipedia pages, e.g. https://en.wikipedia.org/wiki/List_of_members_of_the_Folketing#References #101 
- [x] a "Download this as CSV" button #99

**Comment by tmtmtmtm** [comment]
@zarino — In case it impacts any of your thinking, this is the main page that will go live for every country *before* any of the other pages — i.e. this should to be capable of standing on its own without links to Person or Party pages etc initially, until "Stage 2" for that country is ready, as well as working when those things *do* become links.

(However, if required, we _could_ have two versions of the page, depending on whether the Country is at the next stage or not. I'd prefer not to, but if the design works better like that, then it's doable.)

**Comment by zarino** [comment]
I've started design tweaks in the branch [issues/96-term-table-design](https://github.com/mysociety/popolo-viewer-sinatra/compare/issues/96-term-table-design?expand=1)
